document.writeln("<meta charset=\'UTF-8\'>");
document.writeln("<meta name=\'viewport\' content=\'width=device-width, initial-scale=1.0\'>");
document.writeln("<meta http-equiv=\'X-UA-Compatible\' content=\'ie=edge\'>");
document.writeln("<link href=\'/src/styles/bootstrap.min.css\' rel=\'stylesheet\'>");
document.writeln("<link href=\'/src/styles/style.css\' rel=\'stylesheet\'>");
document.writeln("<script src=\'/statics/js/axios.js\'></script>");
document.writeln("<script src=\'/statics/js/axios.min.js\'></script>");
document.writeln("<script src=\'/statics/js/script.js\'></script>");
document.writeln("");
document.writeln("<script src=\'https://cdn.staticfile.org/jquery/2.1.1/jquery.min.js\'></script>");
document.writeln("<script src=\'https://cdn.staticfile.org/twitter-bootstrap/3.3.7/js/bootstrap.min.js\'></script>");
document.writeln("<script src=\'/src/script/libs/bootstrap.min.js\'></script>");
document.writeln("<script src=\'/src/script/libs/jquery.min.js\'></script>");
document.writeln("<title>欢迎使用502汽修管理系统</title>");