document.writeln("<div class=\'container-fluid\'>");
document.writeln("    <div class=\'row\'>");
document.writeln("        <!--左导航栏-->");
document.writeln("        <div class=\'hidden-xs  col-md-2\'>");
document.writeln("            <div class=\'list-group\'>");
document.writeln("                <a class=\'list-group-item list-group-item-success\'>");
document.writeln("                    功能");
document.writeln("                </a>");
document.writeln("                <a class=\'list-group-item\' href=\'/change_password\'>更改密码</a>");
document.writeln("                <a class=\'list-group-item\' href=\'/take_orders\'>接单</a>");
document.writeln("                <a class=\'list-group-item\' href=\'/s_check_orders\'>查看接单记录</a>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("        <!--右导航栏-->");
document.writeln("        <div class=\'col-xs-10\' id=\'con\'>");
document.writeln("            <div class=\'container-fluid\'>");
document.writeln("                <div id=\'test_div\'>");
document.writeln("");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("</div>");