document.writeln("<div class=\'container-fluid\'>");
document.writeln("    <div class=\'row\'>");
document.writeln("        <!--左导航栏-->");
document.writeln("        <div class=\'hidden-xs  col-md-2\'>");
document.writeln("            <div class=\'list-group\'>");
document.writeln("                <a class=\'list-group-item list-group-item-success\'>");
document.writeln("                    功能");
document.writeln("                </a>");
document.writeln("                <a class=\'list-group-item\' data-toggle=\'modal\' data-target=\'#change_info\' style=\'cursor:pointer\' onclick=\'userinfo()\'>更改个人信息</a>")
document.writeln("                <a class=\'list-group-item\' href=\'/change_password\'>更改密码</a>");
document.writeln("                <a class=\'list-group-item\' href=\'/u_check_orders\' style=\'cursor:pointer\'>查看申请详情</a>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("			<!--右导航栏-->");
document.writeln("");
document.writeln("			<div class=\'col-md-9\' id=\'con\' >");
document.writeln("				<div class=\'col-md-3 col-md-offset-5\' align=\'left\'>");
document.writeln("					<label style=\'color: darkgreen;font-size:50px\' align=\'left\'>车 辆 信 息</label>");
document.writeln("				</div>");
document.writeln("				<div class=\'col-md-3 col-md-offset-1\' align=\'right\'>");
document.writeln("					<br></br>");
document.writeln("					<a type=\'button\' data-toggle=\'modal\' data-target=\'#add_car\' data-backdrop=\'static\' style=\'font-size: 40px;background-color: #0099CC;color: white;display:inline-block;box-shadow: inset 1px -1px 1px #444, inset -1px 1px 1px #444;\'>新增车辆</a>");
document.writeln("				</div>");
document.writeln("			</div>");
document.writeln("");
document.writeln("			<!--第一辆车-->");
document.writeln("			<div class=\'col-md-9\' style=\'background-color: #dad4fa;box-shadow: inset 1px -1px 1px #444, inset -1px 1px 1px #444;border-radius: 20px\'>");
document.writeln("				<div class=\'col-md-2\' align=\'center\'>");
document.writeln("					<img src=\'/statics/user/汽车.png\' width=\'210px\' >");
document.writeln("				</div>");
document.writeln("				<div class=\'col-md-4\' style=\'box-shadow: inset 1px -1px 0px #444;\'>");
document.writeln("					<img src=\'/show_plate?license_number=沪SHU502\' height=\'100px\'  >");
document.writeln("					<h4 style=\'font-size: 25px\'>很土的黄·很贵的车·很敞的篷</h4>");
document.writeln("					<h4 style=\'display:inline;font-size: 25px\'>车架号：11111111111111111</h4>");
document.writeln("				</div>");
document.writeln("				<div class=\'col-md-6\' align=\'right\' height=\'100px\'>");
document.writeln("					<br></br><br></br>");
document.writeln("					<a class=\'col-md-5\' align=\'center\' type=\'button\' data-toggle=\'modal\' data-target=\'#add_car\' data-backdrop=\'static\' style=\'font-size: 40px;color: white;background-color: #f3b1a9;display:inline-block;box-shadow: inset 1px -1px 1px #444, inset -1px 1px 1px #444;\'>历史维修记录</a>");
document.writeln("					<a class=\'col-md-5 col-md-offset-1\' align=\'center\' type=\'button\' data-toggle=\'modal\' data-target=\'#add_car\' data-backdrop=\'static\' style=\'font-size: 40px;color: white;background-color: #f3b1a9;display:inline-block;box-shadow: inset 1px -1px 1px #444, inset -1px 1px 1px #444;\'>新增维修委托</a>");
document.writeln("				</div>");
document.writeln("			</div>");
document.writeln("");
document.writeln("			<div class=\'col-md-9\' ><br></br></div>");
document.writeln("");
document.writeln("			<!--第二辆车-->");
document.writeln("			<div class=\'col-md-9 col-md-offset-2\' style=\'background-color: #dad4fa;box-shadow: inset 1px -1px 1px #444, inset -1px 1px 1px #444;border-radius: 20px\'>");
document.writeln("				<div class=\'col-md-2\' align=\'center\'>");
document.writeln("					<img src=\'/statics/user/汽车.png\' width=\'210px\' >");
document.writeln("				</div>");
document.writeln("				<div class=\'col-md-4\' style=\'box-shadow: inset 1px -1px 0px #444;\'>");
document.writeln("					<img src=\'/statics/license plates/沪A666666.jpg\' height=\'100px\'  >");
document.writeln("					<h4 style=\'font-size: 25px\'>很土的黄·很贵的车·很敞的篷</h4>");
document.writeln("					<h4 style=\'display:inline;font-size: 25px\'>车架号：11111111111111111</h4>");
document.writeln("				</div>");
document.writeln("				<div class=\'col-md-6\' align=\'right\' height=\'100px\'>");
document.writeln("					<br></br><br></br>");
document.writeln("					<a class=\'col-md-5\' align=\'center\' type=\'button\' data-toggle=\'modal\' data-target=\'#add_car\' data-backdrop=\'static\' style=\'font-size: 40px;color: white;background-color: #f3b1a9;display:inline-block;box-shadow: inset 1px -1px 1px #444, inset -1px 1px 1px #444;\'>历史维修记录</a>");
document.writeln("					<a class=\'col-md-5 col-md-offset-1\' align=\'center\'  type=\'button\' data-toggle=\'modal\' data-target=\'#add_car\' data-backdrop=\'static\' style=\'font-size: 40px;color: white;background-color: #f3b1a9;display:inline-block;box-shadow: inset 1px -1px 1px #444, inset -1px 1px 1px #444;\'>新增维修委托</a>");
document.writeln("				</div>");
document.writeln("			</div>");
document.writeln("<!-- 更改个人信息 -->");
document.writeln("<div class=\'modal fade\' id=\'change_info\' tabindex=\'-1\' role=\'dialog\' aria-labelledby=\'myModalLabel\' aria-hidden=\'true\'>");
document.writeln("    <div class=\'modal-dialog\'>");
document.writeln("        <div class=\'modal-content\'>");
document.writeln("            <div class=\'modal-header\'>");
document.writeln("                <button type=\'button\' class=\'close\' data-dismiss=\'modal\' aria-hidden=\'true\' >&times;</button>");
document.writeln("                <h3 class=\'modal-title\' id=\'changeUserInfo\'>更改个人信息</h3>");
document.writeln("            </div>");
document.writeln("            <div class=\'modal-body\'>");
document.writeln("                <img src=\'/statics/user/真实姓名.png\' width=\'20px\'>");
document.writeln("                <label style=\'font-size:15px;width: 100px;\'>姓名：</label>");
document.writeln("                <input id=\'name\' type=\'text\' placeholder=\'请输入姓名\'/><br></br>");
document.writeln("");
document.writeln("                <img src=\'/statics/user/公司.png\' width=\'20px\'>");
document.writeln("                <label style=\'font-size:15px;width: 100px;\'>性质：</label>");
document.writeln("                <select id=\'property\'>");
document.writeln("                    <option value=\'个人\' selected>个人</option>");
document.writeln("                    <option value=\'公司\'>公司</option>");
document.writeln("                </select><br></br>");
document.writeln("");
document.writeln("                <img src=\'/statics/user/联系人.png\' width=\'20px\'>");
document.writeln("                <label style=\'font-size:15px;width: 100px;\'>联系人：</label>");
document.writeln("                <input id=\'contact_person\' type=\'text\' placeholder=\'请输入联系人\'/><br></br>");
document.writeln("");
document.writeln("                <img src=\'/statics/user/联系人.png\' width=\'20px\'>");
document.writeln("                <label style=\'font-size:15px;width: 100px;\'>联系电话：</label>");
document.writeln("                <input id=\'contact_tel\' type=\'text\' readonly=\'readonly\' value=\'13472413472\'/><br></br>");
document.writeln("");
document.writeln("                <img src=\'/statics/user/联系人.png\' width=\'20px\'>");
document.writeln("                <label style=\'font-size:15px;width: 100px;\'>折扣率：</label>");
document.writeln("                <input id=\'contact_person\' type=\'text\' readonly=\'readonly\' " +
    "value=\'100%\'/><br></br>");
document.writeln("");
document.writeln("            </div>");
document.writeln("            <form class=\'modal-footer\'>");
document.writeln("                <label style=\'font-size:1px;width: 80px;color: red;\'>没有再次确认哦，真的</label>");
document.writeln("                <button type=\'button\' class=\'btn btn-primary\' onclick=\'changeinfo()\' id=\'confirmChangeInfo\'>确认更改</button>");
document.writeln("                <button type=\'button\' class=\'btn btn-default\' data-dismiss=\'modal\'>取消</button>");
document.writeln("            </form>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("</div>");
document.writeln("");
document.writeln("<!-- 新增车辆 -->");
document.writeln("<div class=\'modal fade\' id=\'add_car\' tabindex=\'-1\' role=\'dialog\' aria-labelledby=\'myModalLabel\' aria-hidden=\'true\'>");
document.writeln("    <div class=\'modal-dialog\'>");
document.writeln("        <div class=\'modal-content\'>");
document.writeln("            <div class=\'modal-header\'>");
document.writeln("                <button type=\'button\' class=\'close\' data-dismiss=\'modal\' aria-hidden=\'true\'>&times;</button>");
document.writeln("                <h3 class=\'modal-title\' id=\'addNewVehicle\'>新增车辆</h3>");
document.writeln("            </div>");
document.writeln("            <div class=\'modal-body\'>");
document.writeln("                <img src=\'/statics/user/井号.png\' width=\'20px\'>");
document.writeln("                <label style=\'font-size:15px;width: 80px;\'>车架号：</label>");
document.writeln("                <input id=\'number\' type=\'text\' onchange=\'check_number()\' placeholder=\'请输入车架号\'/>");
document.writeln("                <span id=\'checktext1\'></span> <br></br>");
document.writeln("");
document.writeln("                <img src=\'/statics/user/车牌.png\' width=\'20px\'>");
document.writeln("                <label style=\'font-size:15px;width: 80px;\'>车牌号：</label>");
document.writeln("                <input id=\'license_number\' type=\'text\' onchange=\'check_license_number()\' placeholder=\'请输入车牌号\'/>");
document.writeln("                <img src=\'/statics/user/问号.png\' width=\'20px\'>");
document.writeln("                <span id=\'checktext2\'></span> <br></br>");
document.writeln("");
document.writeln("                <img src=\'/statics/user/颜色.png\' width=\'20px\'>");
document.writeln("                <label style=\'font-size:15px;width: 80px;\'>车辆颜色：</label>");
document.writeln("                <input id=\'color\' type=\'text\' placeholder=\'请输入车辆颜色\'/><br></br>");
document.writeln("");
document.writeln("                <img src=\'/statics/user/车型.png\' width=\'20px\'>");
document.writeln("                <label style=\'font-size:15px;width: 80px;\'>车型：</label>");
document.writeln("                <input id=\'model\' type=\'text\' placeholder=\'请输入车型\'/><br></br>");
document.writeln("");
document.writeln("                <img src=\'/statics/user/类别.png\' width=\'20px\'>");
document.writeln("                <label style=\'font-size:15px;width: 80px;\'>车辆类别：</label>");
document.writeln("                <input id=\'type\' type=\'text\' placeholder=\'请输入车辆类别\'/><br></br>");
document.writeln("            </div>");
document.writeln("            <form class=\'modal-footer\'>");
document.writeln("                <label style=\'font-size:1px;width: 80px;color: red;\'>没有再次确认哦，真的</label>");
document.writeln("                <button type=\'button\' class=\'btn btn-primary\' onclick=\'checkVehicle()\' id=\'confirmAddVehicle\'>确认新增</button>");
document.writeln("                <button type=\'button\' class=\'btn btn-default\' data-dismiss=\'modal\'>取消</button>");
document.writeln("            </form>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("</div>");